### ISSUE TITLE
Release not appearing on b.org? 

### ISSUE THREAD

**Issue by jenlampton** [irinaz/harris_flexible#3]
From @klonos in https://github.com/backdrop-ops/contrib/issues/569#issuecomment-976172735

> You seem to have done everything right @irinaz but although the release was created properly in GitHub, for some reason the project node and the respective release node were not created in b.org.

> @jenlampton have you seen this happen before? Any idea what might be wrong?

**Comment by irinaz** [comment]
I delete release and created new one and it seems to work. 
Thanks, Irina
